### ISSUE TITLE
Test on VE settings

### ISSUE THREAD

**Issue by chen-hao-chao** [AlexiaJM/score_sde_fast_sampling#1]
Hi,
I really like your work and I wanted to use your method on VE settings. 

I have tried this code on sub-VP settings, but have trouble under VE settings. Do you have any helpful comments on how I should use your code to sample from a pretrained VE model? 

(Specifically, I would like to evaluate this code on the configuration "cifar10_deep_continuous_ve.py".)

Thanks!

**Comment by AlexiaJM** [comment]
Hi,

Any of these three lines should work:
https://github.com/AlexiaJM/score_sde_fast_sampling/blob/4805a20bcb74e7a8da306c5bc0b5fe735c76b970/experiments.sh#L129
https://github.com/AlexiaJM/score_sde_fast_sampling/blob/4805a20bcb74e7a8da306c5bc0b5fe735c76b970/experiments.sh#L132
https://github.com/AlexiaJM/score_sde_fast_sampling/blob/4805a20bcb74e7a8da306c5bc0b5fe735c76b970/experiments.sh#L135

You just need to change --workdir to the directory of your pretrained models in ./checkpoints/.


Alexia

**Comment by chen-hao-chao** [comment]
Thank you so much. 
I successfully sampled from a pretrained VE model using adaptive method under "cifar10_deep_continuous_ve.py" settings.
