### ISSUE TITLE
pytorch implementation and ODE

### ISSUE THREAD

**Issue by gwang-kim** [AlexiaJM/score_sde_fast_sampling#2]
Hi, thanks for your great works.

Do you have any plan to implement the codes with Pytorch?
And can this method be applied as an ODE solver where the forward and reverse processes are deterministic?

**Comment by AlexiaJM** [comment]
Sorry for the long delay. I added it, see the new ReadMe: https://github.com/AlexiaJM/score_sde_fast_sampling/blob/main/README.md#2021-09-21-using-the-gottagofast-sampler-in-torch

**Comment by AlexiaJM** [comment]
For ODE solving, you could use Heun's method instead of RK45, by changing the method in this line: https://github.com/yang-song/score_sde_pytorch/blob/1618ddea340f3e4a2ed7852a0694a809775cf8d0/sampling.py#L474. But ODE solving is much worse for VE than SDE solving , just keep that in mind.
